apiVersion: apps/v1
kind: Deployment
metadata:
  name: automation-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: automation
  template:
    metadata:
      labels:
        app: automation
    spec:
      containers:
      - name: automation
        image: nayan1103/automation:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: automation-service
spec:
  selector:
    app: automation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
